INSERT INTO TEAM_GAME VALUES (1,'Valorant');
INSERT INTO TEAM_GAME VALUES (2,'CS:GO');
INSERT INTO TEAM_GAME VALUES (3,'League of Legends');
INSERT INTO TEAM_GAME VALUES (4,'Rocket League');
INSERT INTO TEAM_GAME VALUES (5,'Dota 2');
COMMIT;