INSERT INTO TEAM_TOURNAMENT VALUES (1,1);
INSERT INTO TEAM_TOURNAMENT VALUES (2,1);
INSERT INTO TEAM_TOURNAMENT VALUES (3,3);
INSERT INTO TEAM_TOURNAMENT VALUES (4,4);
INSERT INTO TEAM_TOURNAMENT VALUES (5,5);
COMMIT;