INSERT INTO TEAM (Team_ID,Team_Name,Captain_ID) VALUES (1,'Red Hawks',NULL);
INSERT INTO TEAM VALUES (2,'Blue Wolves',NULL);
INSERT INTO TEAM VALUES (3,'Green Titans',NULL);
INSERT INTO TEAM VALUES (4,'Yellow Knights',NULL);
INSERT INTO TEAM VALUES (5,'Black Dragons',NULL);
COMMIT;