INSERT INTO TOURNAMENT_GAME VALUES (1,'Valorant');
INSERT INTO TOURNAMENT_GAME VALUES (2,'CS:GO');
INSERT INTO TOURNAMENT_GAME VALUES (3,'Dota 2');
INSERT INTO TOURNAMENT_GAME VALUES (1,'CS:GO');
INSERT INTO TOURNAMENT_GAME VALUES (4,'Rocket League');
COMMIT;